sample_app/config/routes.rb
Rails.application.routes.draw do
  

  root 'static_pages#home' # get '/' => 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  get '/contact' => 'static_pages#contact'
  get '/login' => 'static_pages#login'
  get '/signup' => 'users#new'

  

end

sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def hello
    render text: "hello, world!"
  end
end

sample_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def login
  end
end

sample_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

sample_app/app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

sample_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
  
end

sample_app/app/helpers/users_helper.rb
module UsersHelper
end

sample_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

sample_app/app/views/layouts/_header.html.erb
<header class="navbar narbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <!-- <li><%= link_to "Contact", contact_path %></li> -->
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Log in", login_path %></li>
  </div>
</header>

sample_app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

sample_app/app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<body>
  <h1>StaticPages#about</h1>
  <p>Find me in app/views/static_pages/about.html.erb</p>
</body>

sample_app/app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<body>
  <h1>StaticPages#contact</h1>
  <p>Find me in app/views/static_pages/contact.html.erb</p>
</body>

sample_app/app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<body>
  <h1>StaticPages#help</h1>
  <p>Find me in app/views/static_pages/help.html.erb</p>
</body>

sample_app/app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">

  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the homepage
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

</div>

<%= link_to image_tag("https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Ruby_On_Rails_Logo.svg/150px-Ruby_On_Rails_Logo.svg.png", alt: "Rails logo"), 'http://rubyonrails.org' %>

sample_app/app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign Up</h1>
<p>Find me in app/views/users/new.html.erb</p>